"use client";

import { useState } from "react";
import { useTheme } from "@/components/theme-context";

const principles = [["01", "Stay curious", "Ask the question behind the question, then keep learning."], ["02", "Make it useful", "Good ideas earn their place by helping someone move forward."], ["03", "Leave room", "We make space for different perspectives, new skills, and better ways." ]];
const journey = [["01", "Say hello", "Share what you are curious about and where you want to grow."], ["02", "Meet the team", "A relaxed conversation to learn how we think and work together."], ["03", "Make something", "A small, thoughtful exercise shows us how you approach a problem."], ["04", "Find your place", "We agree on the right next step when the fit is mutual." ]];

function Arrow(){return <svg className="icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h13M13 6l6 6-6 6"/></svg>}
function Spark(){return <svg className="icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 1.8 6.2L20 11l-6.2 1.8L12 19l-1.8-6.2L4 11l6.2-1.8Z"/></svg>}

export default function CareersPage(){const {dark}=useTheme();const [chatOpen,setChatOpen]=useState(false);return <main className={dark?"home home-dark careers-page":"home careers-page"}>
  <section className="career-hero section-shell" aria-labelledby="careers-title"><div><p className="eyebrow">Careers at Miners</p><h1 id="careers-title">Build work that moves people forward.</h1><p>We are a small, thoughtful product studio looking for curious people who care about the details and the difference good software can make.</p><div className="hero-actions"><a className="button button-dark" href="#openings">Explore opportunities <Arrow/></a><a className="button button-ghost" href="mailto:hello@miners.group?subject=Careers%20at%20Miners">Say hello</a></div></div><div className="career-hero-art" role="img" aria-label="Abstract colorful collaboration visual"><span>CURIOUS</span><span>CAPABLE</span><span>KIND</span></div></section>
  <section className="career-section section-shell" aria-labelledby="why-title"><div className="career-heading"><p className="eyebrow">Why join</p><h2 id="why-title">A place to do your best, most human work.</h2></div><div className="career-principles">{principles.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="career-expect section-shell" aria-labelledby="expect-title"><div className="career-expect-art" aria-hidden="true"><span>01</span><span>02</span><span>03</span></div><div><p className="eyebrow">What to expect</p><h2 id="expect-title">Small teams. Clear ownership. Real momentum.</h2><p>You will work close to the people making decisions, see your ideas become real, and get the support to keep sharpening your craft.</p></div></section>
  <section className="career-journey section-shell" aria-labelledby="journey-title"><div className="career-heading"><p className="eyebrow">Hiring journey</p><h2 id="journey-title">A clear process, with humans in it.</h2></div><ol>{journey.map(([n,t,d])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></section>
  <section id="openings" className="career-openings section-shell" aria-labelledby="openings-title"><div><p className="eyebrow">Roles &amp; internships</p><h2 id="openings-title">Good people are always worth meeting.</h2><p>We do not have live openings published yet. If Miners feels like your kind of place, send a note and tell us what you would love to make.</p><a className="button button-dark" href="mailto:hello@miners.group?subject=Future%20opportunities%20at%20Miners">Share your work <Arrow/></a></div><div className="career-openings-card"><strong>Sample pathways</strong><p>Product design · Frontend engineering · Product strategy · Internships</p><span>Openings will be published here.</span></div></section>
  <section className="conversion section-shell" aria-labelledby="careers-contact-title"><div className="conversion-heading"><p className="eyebrow">Let&apos;s talk</p><h2 id="careers-contact-title">Ready when you are.</h2></div><div className="conversion-grid"><article className="conversion-panel project-panel"><p className="eyebrow">Start project</p><h3>Have something ambitious in mind?</h3><p>Tell us what you want to build, and we&apos;ll help shape the clearest path forward.</p><a className="button button-mint" href="mailto:hello@miners.group">Start a project <Arrow/></a></article><article className="conversion-panel chat-panel"><p className="eyebrow">Free 30-minute chat</p><h3>Still exploring? Coffee is on us.</h3><p>Book a relaxed conversation to discuss an idea, challenge, or opportunity with no commitment.</p><a className="button button-blue" href="mailto:hello@miners.group">Book a coffee chat <Arrow/></a></article></div></section>
  <button type="button" className="ask-miners focus-ring" aria-expanded={chatOpen} onClick={()=>setChatOpen(v=>!v)}><Spark/> Ask Miners</button>{chatOpen&&<div className="chat-popover glass-panel" role="dialog" aria-label="Ask Miners chat"><strong>What are you building?</strong><p>Tell us a little about your idea.</p><a href="mailto:hello@miners.group">Send a note <Arrow/></a></div>}
 </main>}
