/* eslint-disable @next/next/no-html-link-for-pages */
"use client";

import { useMemo, useState } from "react";
import { useTheme } from "@/components/theme-context";

type Filter = "All work" | "Web platforms" | "Mobile products" | "Custom systems";
type Project = { category: Exclude<Filter, "All work">; title: string; challenge: string; product: string; outcome: string; tags: string[]; tone: string };

const filters: Filter[] = ["All work", "Web platforms", "Mobile products", "Custom systems"];
const projects: Project[] = [
  { category: "Web platforms", title: "Campus Flow", challenge: "A fragmented digital journey made everyday campus tasks harder to find.", product: "A sample web platform concept for one clear student workspace.", outcome: "Sample outcome: simpler navigation and a calmer task flow.", tags: ["Strategy", "Design", "Engineering"], tone: "project-tone-sky" },
  { category: "Custom systems", title: "Atlas Workspace", challenge: "Teams needed a shared view of work without adding another noisy tool.", product: "A sample operations workspace with connected views and focused actions.", outcome: "Sample outcome: a clearer handoff between planning and delivery.", tags: ["Strategy", "Design", "Engineering"], tone: "project-tone-mint" },
  { category: "Mobile products", title: "Open Portal", challenge: "A mobile-first service needed a more welcoming front door.", product: "A sample mobile product direction built around a short, confident journey.", outcome: "Sample outcome: fewer steps between intent and useful action.", tags: ["Research", "Design", "Prototype"], tone: "project-tone-lilac" },
  { category: "Custom systems", title: "Northstar Labs", challenge: "A growing team needed product decisions to stay visible and aligned.", product: "A sample product system combining a decision map and delivery signals.", outcome: "Sample outcome: a shared language for the next release.", tags: ["Product", "Design", "Engineering"], tone: "project-tone-blue" },
];

function Arrow() { return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="icon"><path d="M5 12h13M13 6l6 6-6 6" /></svg>; }
function Spark() { return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="icon"><path d="m12 3 1.8 6.2L20 11l-6.2 1.8L12 19l-1.8-6.2L4 11l6.2-1.8Z" /></svg>; }

export default function ProjectsPage() {
  const { dark } = useTheme();
  const [filter, setFilter] = useState<Filter>("All work");
  const [chatOpen, setChatOpen] = useState(false);
  const visibleProjects = useMemo(() => filter === "All work" ? projects : projects.filter((project) => project.category === filter), [filter]);
  return <main className={dark ? "home home-dark projects-page" : "home projects-page"}>
    <section className="projects-hero section-shell" aria-labelledby="projects-title"><div><p className="eyebrow">Projects</p><h1 id="projects-title">Thoughtful software for meaningful momentum.</h1><p>Explore a set of sample case studies showing how Miners turns complex questions into clear digital products.</p><a className="button button-dark" href="/#contact">Start a project <Arrow /></a></div><aside className="projects-hero-art" aria-hidden="true"><span>Discover</span><span>Build</span><span>Improve</span></aside></section>
    <section className="outcome-map section-shell" aria-labelledby="outcomes-title"><p className="eyebrow">How we think</p><h2 id="outcomes-title">Good work moves from question to confidence.</h2><div className="outcome-grid"><article><span>01</span><h3>Discover</h3><p>Find the signal in the brief, the workflow, and the people it serves.</p></article><article><span>02</span><h3>Build</h3><p>Turn a shared direction into a product people can use and trust.</p></article><article><span>03</span><h3>Improve</h3><p>Keep learning after launch with useful feedback and focused iteration.</p></article></div></section>
    <section className="projects-work section-shell" aria-labelledby="work-title"><div className="projects-heading"><div><p className="eyebrow">Featured work</p><h2 id="work-title">Sample projects, clearly labelled.</h2></div><p>These are representative examples, not client claims. Verified project evidence can replace the sample content when available.</p></div><div className="project-filters" role="group" aria-label="Filter sample projects">{filters.map((item) => <button type="button" className={`project-filter focus-ring${filter === item ? " is-active" : ""}`} aria-pressed={filter === item} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="projects-grid" aria-live="polite">{visibleProjects.map((project) => <article className="case-study-card" key={project.title}><div className={`case-study-art ${project.tone}`} aria-hidden="true"><span>Sample case study</span></div><div className="case-study-copy"><p className="case-category">{project.category}</p><h3>{project.title}</h3><dl><div><dt>Challenge</dt><dd>{project.challenge}</dd></div><div><dt>Product</dt><dd>{project.product}</dd></div><div><dt>Outcome</dt><dd>{project.outcome}</dd></div></dl><ul className="case-tags">{project.tags.map((tag) => <li key={tag}>{tag}</li>)}</ul><a className="case-link focus-ring" href="/#contact">Discuss a similar challenge <Arrow /></a></div></article>)}</div>{visibleProjects.length === 0 && <p role="status">No sample projects match this filter yet.</p>}</section>
    <section className="proof-framework section-shell" aria-labelledby="proof-framework-title"><p className="eyebrow">Proof framework</p><h2 id="proof-framework-title">We look for progress in three directions.</h2><div className="proof-framework-grid"><article><span>01</span><h3>Business impact</h3><p>Does the product make an important decision, workflow, or opportunity clearer?</p></article><article><span>02</span><h3>User experience</h3><p>Can people understand what to do next without unnecessary friction?</p></article><article><span>03</span><h3>Technical quality</h3><p>Is the foundation reliable enough to evolve as the team and product grow?</p></article></div></section>
    <section className="delivery-approach section-shell" aria-labelledby="approach-title"><div><p className="eyebrow">Delivery approach</p><h2 id="approach-title">Visible progress, thoughtful decisions.</h2><p>We keep the work close to the people who know the problem best, with clear checkpoints from first conversation to launch.</p></div><ol><li><span>01</span><strong>Align</strong><p>Agree on the clearest problem and the right first step.</p></li><li><span>02</span><strong>Make</strong><p>Share tangible work early and improve it together.</p></li><li><span>03</span><strong>Learn</strong><p>Use feedback to decide what deserves the next investment.</p></li></ol></section>
    <section className="conversion section-shell" aria-labelledby="projects-contact"><div className="conversion-heading"><p className="eyebrow">Let&apos;s talk</p><h2 id="projects-contact">Ready to make the next move clearer?</h2></div><div className="conversion-grid"><article className="conversion-panel project-panel"><p className="eyebrow">Start project</p><h3>Have a product question to solve?</h3><p>Tell us what you want to build and we&apos;ll help shape the clearest path forward.</p><a className="button button-mint" href="mailto:hello@miners.group">Start a project <Arrow /></a></article><article className="conversion-panel chat-panel"><p className="eyebrow">Free 30-minute chat</p><h3>Still exploring? Coffee is on us.</h3><p>Book a relaxed conversation with no commitment.</p><a className="button button-blue" href="mailto:hello@miners.group">Book a coffee chat <Arrow /></a></article></div></section>
    <button type="button" className="ask-miners focus-ring" aria-expanded={chatOpen} onClick={() => setChatOpen(!chatOpen)}><Spark /> Ask Miners</button>{chatOpen && <div className="chat-popover glass-panel" role="dialog" aria-label="Ask Miners chat"><strong>What are you building?</strong><p>Tell us a little about your idea.</p><a href="mailto:hello@miners.group">Send a note <Arrow /></a></div>}
  </main>;
}
